CREATE TABLE `participants` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador numèric del corredor',
  `registrationDate` datetime NOT NULL COMMENT 'data de creació del registre',
  `modificationDate` datetime NOT NULL COMMENT 'data del últim canvi del registre',
  `idCard` varchar(11) COLLATE utf8_spanish_ci NOT NULL COMMENT 'codi identificació fiscal',
  `birthDate` date NOT NULL COMMENT 'data de naixement del participant',
  `name` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'nom del participant',
  `firstSurname` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'primer cognom del participant',
  `secondSurname` varchar(25) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'segón cognom del participant',
  `gender` enum('Home','Dona') COLLATE utf8_spanish_ci NOT NULL COMMENT 'gènere del participant',
  `street` varchar(80) COLLATE utf8_spanish_ci NOT NULL COMMENT 'adreça on viu el participant (carrer, número, pis...)',
  `zipCode` varchar(7) COLLATE utf8_spanish_ci NOT NULL COMMENT 'codi postal de l''adreça del participant',
  `city` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'nom de la població corresponent a l''adreça postal del participant',
  `state` varchar(25) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'provincia de l''adreça del participant',
  `country` varchar(25) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'païs de l''adreça del participant',
  `phoneNumber` varchar(15) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'telèfon del participant',
  `emergencyPhoneNumber` varchar(15) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'telèfon en cas de urgència durant la cursa',
  `email` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'correu electrònic del participant',
  `operational` int(1) NOT NULL COMMENT 'estat de les dades del participant. Actives o inactives',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='dades dels corredors que s''han inscrit en alguna cursa';